version: "3.9"
services:
  postgres:
    container_name: go_subscription_service
    image: postgres:16
    user: root
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - go-sub-service-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - ./db-data/redis/:/data

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: always
networks:
  go-sub-service-network:
    driver: bridge
